### ISSUE TITLE
"There was an error preparing your transaction"

### ISSUE THREAD

**Issue by titusdecali** [privy-io/auth-demo#173]
I'm getting an error when trying to complete a transaction with ` "@privy-io/react-auth": "^1.51.1"`

`"There was an error preparing your transaction"`

```
unsignedTx = {
    from :  "0x30302ed7e8b5f947a7f5F0Ca259478E01b5311d5"
    to: "0x74e5B82B0c56b4d890F7dD28a377f6E77698Ecb4"
    value: "4800000000000"
}
```

```
      onClick={async () => {
        const txReceipt = await sendTransaction(unsignedTx, uiConfig)
      }}
```

I've no idea how to troubleshoot this without better error handling from Privy.

When I pass the same payload to Web3 to run the transaction it works fine.

@Koleok are you a member of this team? I see you've updated a README but there are no public members of this organization.

~@privy.io: PLEASE WATCH YOUR ISSUES! YOU'VE NOT ANSWERED A SINGLE ONE IN ANY REPO!!!!!!!!!~
(thanks ^^)

![SHOT 18 25 58@2x](https://github.com/privy-io/auth-demo/assets/4532534/ed09c1ee-6009-42a2-b810-85eefeae3c5b)

**Comment by dabangarang2** [comment]
Hi @titusdecali, apologies for the delay, as you are correct-- we have not been actively monitoring the public repo issues, as all of our issues and dev support is handled in our active developer's slack. (invite link [here](https://join.slack.com/t/privy-developers/shared_invite/zt-1w4b6qbr5-C1jEP6Bqa5TODe3Mg6ggPw)!) If you are able to start a thread in the dev-support channel there, I am more than happy to assist with this issue there. Off the bat, a few questions I had:
- Generally the error messages for this sort of issue can be found in your browser Network and Console tab. Are there any more detailed errors there that you can share with us?
- Does upgrading to the latest SDK version (1.52.2) fix this issue? We added some improvements to embedded wallet transaction handling in recent SDK updates.

**Comment by sternhenri** [comment]
Just the same -- thanks for calling us out @titusdecali -- we'll be on top of these issues moving forward: it's an essential part of any OSS repo and this was an oversight on our part. Feel free to jump into Slack if helpful, but we'll get these sorted here as well. We appreciate you!

**Comment by titusdecali** [comment]
> we have not been actively monitoring the public repo issues, as these are demo repositories, and all of our issues and dev support is handled in our active developer's slack

That makes sense. Since there wasn't a `"@privy-io/react-auth"` repo, I felt a bit weird posting in the example projects, but didn't know of anywhere else to ask for help.

Thank you for answering all of my issues. ^^


> Does upgrading to the latest SDK version (1.52.2) fix this issue? 
I updated to version `^1.52.4`, but got the same issue.

> Generally the error messages for this sort of issue can be found in your browser Network and Console tab
**Console error (when using `sendTransaction`)**
```
Uncaught Error: cannot dequeue privy:wallet:connect event: no event found for id id-13
    at Da.dequeue (index.js:2499:1)
    at V0 (index.js:2499:1)
    at n (index.js:2499:1)
```

**Network tab: no errors, but here is the data I see:**
```
{
    "jsonrpc": "2.0",
    "id": 45,
    "result": {
        "baseFeePerGas": "0x673585dff",
        "difficulty": "0x0",
        "extraData": "0xd883010d04846765746888676f312e32312e33856c696e7578",
        "gasLimit": "0x1c9c380",
        "gasUsed": "0x1043d75",
        "hash": "0x912e44b28f0086aaa28eb70c78d22a6f31340901c081e59d464e6279f1092398",
        "logsBloom": "0x003160114040d0005a1808758409d1620040505498452240008a010c4a802032422293a0e0100a8aa8099104921419b6e61184a08848e85000101d80a03c6a0ef8580c0940082eb8e892460b020885ae10d000040d4428101181f4d88ba10018120444030b03000d0e34108008144a5bc00300880af91e048289049000d8b404ab4807559118d10898840945950700a53c028101a9ad0288d4f1d4d0125f44a1ee0035384aaa670a002144c452058400ac422a4459185822a100c4938b00421d11081b0600d4084c2810200044bb7c272210c400463e807e284c0622000962211070a54802800c200a07a0a5e10842094900d8085f188441000b2838908c14d9",
        "miner": "0x388c818ca8b9251b393131c08a736a67ccb19297",
        "mixHash": "0x1120436f5ec7a063846ba4387ba4a8cd1163117b911bacf6f6606caf7770fbf8",
        "nonce": "0x0000000000000000",
        "number": "0x1214b62",
        "parentHash": "0x604553546e4e13e0a74f09234b6f8cc4702d5cc4efcb58818f4dc83ec46bd43d",
        "receiptsRoot": "0x3dc51df77e7a90fc7ecf905fc4a25475b6762a8e6540a98ca0e8f7319a3edeb4",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "size": "0xdf65e",
        "stateRoot": "0xe13487371090015e8fc8c081e78706344db798750509fb498fa6274f5b113e0c",
        "timestamp": "0x659b56bf",
        "totalDifficulty": "0xc70d815d562d3cfa955",
        "transactions": [
            "0x28c3bce001713fdb6cd116af841ff3903d10b255733b917a49ba5ad9eed560b3",
          ~... tons more entries here, cut to 1 for brevity
        ],
        "transactionsRoot": "0x2619be9dc442dbb2feb8f8c1edda45f9efa0b45674a8983a55db00db22421970",
        "uncles": [],
        "withdrawals": [
            {
                "address": "0xb665c84e56bf6d6ad1c507f63588dd764301a63d",
                "amount": "0x10c7ae4",
                "index": "0x1d5c916",
                "validatorIndex": "0x377c"
            },
          ~... tons more entries here, cut to 1 for brevity
        ],
        "withdrawalsRoot": "0x6febb0b12b0aca04a8b1c606947bb48ad005556dc302e5e3d636a18f785f12fc"
    }
}
```

**Comment by titusdecali** [comment]
On an account which does not have a Privy wallet generated for it and I try to do a send after connecting a normal Metamask wallet (via privy connect wallet), I am getting the following error:

![SHOT 18 11 12@2x](https://github.com/privy-io/auth-demo/assets/4532534/03a6fcb2-0b9f-4206-b421-a4067d30b6c2)

On a side note, I am curious if I should have the user login to Privy with `login()` method on `usePrivy()` hook before using `sendTransaction()`? I guess if the user only wants to use a normal ETH wallet (metamask, etc) then `login()` wouldn't be required, however based on the above error it seems that a Privy wallet is required, even if they try to just use a metamask wallet.

**Comment by dabangarang2** [comment]
Hey @titusdecali responding in the dev-support thread!

**Comment by titusdecali** [comment]
I would really like to suggest that you open the `@privy-io/react-auth` repo to devs and allow us to leave GitHub issues there. I've never seen a product that required all issues to be directed via a Slack channel, especially one that is on the free tier and thus will lose chat history within a short period of time.

Making issues more visible will save you guys time answering the same questions over and over again, and makes searching for answers easier than via Slack.

Just a thought.

**Comment by dabangarang2** [comment]
Hey @titusdecali, thanks for the feedback -- we've been discussing this internally amongst the team, and are in the process of reviewing how we should go about customer support, especially as our userbase continues to expand. We want to keep you closely in the loop about how our process will change over time, including if we do move towards making our internal repos open to the public, how to do so.

There are quite a few things we would need to do on our end to ensure our core SDKs can be properly Open-Sourced/made public, and we are currently assessing those sorts of things to put on our team's roadmap amongst other things. 

Otherwise, we do ask that for the time being, questions can be directed in our dedicated dev channel, as that's where the best support experience can occur-- plus if you are required to send specific repros or other forms of more secure info (app IDs, addresses, etc.) we can easily do so there!
