### ISSUE TITLE
FEATURE: ETH / ERC20 balances

### ISSUE THREAD

**Issue by titusdecali** [privy-io/auth-demo#175]
Just a nice to have feature I think many devs would appreciate:

**Within Web3, to get balances for ETH or any list of ERC20 tokens from a Web3 wallet, we have to do the following:**
- Request balance from wallet, which gives us only our ETH balance.
- Request balance for every.single.token. we want to get a balance for.

**But, to get balances for any 1 token, we have to:**
- Have the token contract address
- Have (at least) the balance method within the ERC20 ABI

Since we are not using any special methods on any one ERC20 token's contract logic, we don't need the full ABI for each, just part of the ERC20 ABI for the method to fetch blaances.

Figuring out all this stuff is a pain just to show balances of connected Web3 wallets within our apps. Also, it takes a non-insignificant amount of time to get the balance of each wallet from Metamask, etc. so this would be nice to have running in the background as soon as the wallet is connected. 

I imagine we could have a function like `getEthBalance`, `getTokenBalances`, which would return our ETH balance, or an array of balances.

Just a thought.

**Comment by dabangarang2** [comment]
Thanks for the feedback! Agreed that the general process of token querying is a point of friction for general web3 development. I do think that this is definitely more of an issue that other libraries focues on wallet/asset transaction management (such as viem and wagmi) are actively working on, but Developer Experience Problems like these are things we are absolutely tuned in on and trying to find new ways to solve. Will keep you in the loop about we think of regarding this problem!
